export const projects = [
  {
    id: 1,
    title: "Living Room",
    category: "Residential",
    image: "/home-interior.jpg",
  },
  {
    id: 2,
    title: "Office",
    category: "Commercial",
    image: "/home-interior.jpg",
  },
  {
    id: 3,
    title: "Production Area",
    category: "Industrial",
    image: "/home-interior2.jpg",
  },
  {
    id: 4,
    title: "Retail",
    category: "Commercial",
    image: "/home-interior.jpg",
  },
  {
    id: 5,
    title: "Kitchen",
    category: "Residential",
    image: "/home-interior2.jpg",
  },
  {
    id: 6,
    title: "Bed Room",
    category: "Residential",
    image: "/home-interior2.jpg",
  },
  {
    id: 7,
    title: "Dining Room",
    category: "Residential",
    image: "/home-interior2.jpg",
  },
  {
    id: 8,
    title: "Urban Loft",
    category: "Customised Furniture",
    image: "/home-interior.jpg",
  },
  {
    id: 9,
    title: "Dining Room",
    category: "Residential",
    image: "/home-interior2.jpg",
  },
  {
    id: 10,
    title: "Bath Room",
    category: "Residential",
    image: "/home-interior2.jpg",
  },
  {
    id: 11,
    title: "Home Theatre",
    category: "Residential",
    image: "/home-interior2.jpg",
  },
  {
    id: 12,
    title: "Hospitality",
    category: "Commercial",
    image: "/home-interior2.jpg",
  },
  {
    id: 13,
    title: "Health Care",
    category: "Commercial",
    image: "/home-interior2.jpg",
  },
  {
    id: 14,
    title: "Corporate Interior",
    category: "Commercial",
    image: "/home-interior2.jpg",
  },
  {
    id: 15,
    title: "Educational",
    category: "Commercial",
    image: "/home-interior2.jpg",
  },
  {
    id: 16,
    title: "Dining Room",
    category: "Residential",
    image: "/home-interior2.jpg",
  },
  {
    id: 17,
    title: "Storate and Warehouse",
    category: "Industrial",
    image: "/home-interior2.jpg",
  },
  {
    id: 18,
    title: "Office and Administrative",
    category: "Industrial",
    image: "/home-interior2.jpg",
  },
  {
    id: 20,
    title: "Worker Facilities",
    category: "Industrial",
    image: "/home-interior2.jpg",
  },
  {
    id: 21,
    title: "Safety and Utility",
    category: "Industrial",
    image: "/home-interior2.jpg",
  },
  {
    id: 22,
    title: "Loading and Dispatch Area",
    category: "Industrial",
    image: "/home-interior2.jpg",
  },
  {
    id: 23,
    title: "Tables and Chair",
    category: "Customised Furniture",
    image: "/home-interior2.jpg",
  },
  {
    id: 24,
    title: "Sofa and Sets",
    category: "Customised Furniture",
    image: "/home-interior2.jpg",
  },
  {
    id: 25,
    title: "Kitchen Furniture and Accessories",
    category: "Customised Furniture",
    image: "/home-interior2.jpg",
  },
  {
    id: 26,
    title: "Beds",
    category: "Customised Furniture",
    image: "/home-interior2.jpg",
  },
  {
    id: 27,
    title: "Safety and Utility",
    category: "Customised Furniture",
    image: "/home-interior2.jpg",
  },
  {
    id: 28,
    title: "Loading and Dispatch Area",
    category: "Customised Furniture",
    image: "/home-interior2.jpg",
  },
  {
    id: 29,
    title: "Cutting and Shaping",
    category: "Wood and Plywood Crafting",
    image: "/home-interior2.jpg",
  },
  {
    id: 30,
    title: "Carving and Detailing",
    category: "Wood and Plywood Crafting",
    image: "/home-interior2.jpg",
  },
  {
    id: 31,
    title: "Lamination and Finishing",
    category: "Wood and Plywood Crafting",
    image: "/home-interior2.jpg",
  },
  {
    id: 32,
    title: "Assembly and Installation",
    category: "Wood and Plywood Crafting",
    image: "/home-interior2.jpg",
  },
];
